---
- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install system packages.
  become: yes
  become_user: root
  package:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ system_packages }}"

- name: Install flatpak packages.
  flatpak:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    method: user
  loop: "{{ flatpak_packages }}"
