import = [
    "~/.config/alacritty/themes/themes/catppuccin_frappe.toml"
]
live_config_reload = true

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "None"
opacity = 0.9
blur = true

[font]
normal.family = "MesloLGS Nerd Font Mono"

#regular
size = 16

#for video
# size = 35.0
