live_config_reload = true

import = [
    "~/.config/alacritty/themes/themes/catppuccin_frappe.toml"
]

[ env ]
TERM = "xterm-256color"
MY_TERM_PROGRAM = "alacritty"

[window]
padding.x = 10
padding.y = 10

decorations = "Full"
opacity = 0.9
blur = true

[font]
# normal.family = "MesloLGS Nerd Font Mono"
normal.family = "JetBrainsMono Nerd Font Mono"

#regular
size = 16


#for video
# size = 35.0
